
declare module 'react-zondicons' {
  import {SFC} from 'react';
  namespace ReactZondicons {
    export const AddOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const AddSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Adjust :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Airplane :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Album :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const AlignCenter :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const AlignJustified :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const AlignLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const AlignRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Anchor :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Announcement :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Apparel :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowOutlineDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowOutlineLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowOutlineRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowOutlineUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThickDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThickLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThickRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThickUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThinDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThinLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThinRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowThinUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ArrowUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Artist :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const AtSymbol :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Attachment :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Backspace :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BackwardStep :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Backward :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Badge :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BatteryFull :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BatteryHalf :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BatteryLow :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Beverage :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Block :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Bluetooth :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Bolt :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BookReference :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BookmarkCopy2 :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BookmarkCopy3 :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BookmarkOutlineAdd :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BookmarkOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Bookmark :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderAll :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderBottom :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderHorizontal :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderInner :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderNone :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderOuter :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderTop :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BorderVertical :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Box :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BrightnessDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BrightnessUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BrowserWindowNew :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BrowserWindowOpen :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const BrowserWindow :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Bug :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Buoy :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Calculator :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Calendar :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Camera :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ChartBar :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ChartPie :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Chart :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ChatBubbleDots :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheckmarkOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Checkmark :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronOutlineDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronOutlineLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronOutlineRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronOutlineUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CheveronUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Clipboard :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CloseOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CloseSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Close :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CloudUpload :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Cloud :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Code :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Coffee :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Cog :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ColorPalette :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Compose :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ComputerDesktop :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ComputerLaptop :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Conversation :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Copy :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CreditCard :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const CurrencyDollar :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Dashboard :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const DateAdd :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const DialPad :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Directions :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const DocumentAdd :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Document :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const DotsHorizontalDouble :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const DotsHorizontalTriple :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Download :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Duplicate :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const EditCopy :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const EditCrop :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const EditCut :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const EditPencil :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Education :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Envelope :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ExclamationOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ExclamationSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Explore :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Factory :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FastForward :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FastRewind :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Film :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Filter :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Flag :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Flashlight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FolderOutlineAdd :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FolderOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Folder :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FormatBold :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FormatFontSize :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FormatItalic :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FormatTextSize :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const FormatUnderline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ForwardStep :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Forward :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Gift :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Globe :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const HandStop :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const HardDrive :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Headphones :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Heart :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Home :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Hot :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const HourGlass :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const InboxCheck :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const InboxDownload :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const InboxFull :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Inbox :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const IndentDecrease :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const IndentIncrease :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const InformationOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const InformationSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Key :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Keyboard :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Layers :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Library :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LightBulb :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Link :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ListAdd :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ListBullet :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const List :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LoadBalancer :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationCurrent :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationFood :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationGasStation :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationHotel :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationMarina :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationPark :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationRestroom :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LocationShopping :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Location :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LockClosed :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const LockOpen :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Map :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Menu :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Mic :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MinusOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MinusSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MobileDevices :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MoodHappyOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MoodHappySolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MoodNeutralOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MoodNeutralSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MoodSadOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MoodSadSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Mouse :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MusicAlbum :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MusicArtist :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MusicNotes :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const MusicPlaylist :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const NavigationMore :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Network :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const NewsPaper :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Notification :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const NotificationsOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Notifications :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Paste :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const PauseOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const PauseSolid :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Pause :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const PenTool :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Phone :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Photo :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const PhpElephant :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Pin :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const PlayOutline :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Play :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Playlist :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Plugin :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Portfolio :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Printer :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Pylon :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Question :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Queue :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const RadarCopy2 :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Radar :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Radio :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Refresh :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Reload :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ReplyAll :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Reply :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Repost :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const SaveDisk :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ScreenFull :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Search :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Send :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Servers :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Share01 :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ShareAlt :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Share :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Shield :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ShoppingCart :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ShowSidebar :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Shuffle :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const StandBy :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const StarFull :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Station :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const StepBackward :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const StepForward :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Stethoscope :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const StoreFront :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const StrokeWidth :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const SubdirectoryLeft :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const SubdirectoryRight :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Swap :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Tablet :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Tag :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Target :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TextBox :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TextDecoration :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Thermometer :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ThumbsDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ThumbsUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Ticket :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Time :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Timer :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ToolsCopy :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Translate :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Trash :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TravelBus :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TravelCar :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TravelCase :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TravelTaxiCab :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TravelTrain :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const TravelWalk :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Travel :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Trophy :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Tuning :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Upload :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Usb :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const UserAdd :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const UserGroup :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const UserSolidCircle :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const UserSolidSquare :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const User :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Vector :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const VideoCamera :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ViewCarousel :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ViewColumn :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ViewHide :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ViewList :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ViewShow :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ViewTile :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const VolumeDown :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const VolumeMute :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const VolumeOff :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const VolumeUp :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Wallet :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Watch :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const WindowNew :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const WindowOpen :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Window :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const Wrench :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const YinYang :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ZoomIn :SFC<SVGElement|{size?:number;title?:string;className?:string}>
    export const ZoomOut :SFC<SVGElement|{size?:number;title?:string;className?:string}>
  }
  export = ReactZondicons
}